kind: meson

sources:
- kind: git_repo
  url: github:elementary/quick-settings
  track: main
  ref: 1.4.0-21-g425729a4fdc5ec80b355e14c1095a5a004240180

build-depends:
- freedesktop-sdk.bst:public-stacks/buildsystem-meson.bst
- freedesktop-sdk.bst:components/pkg-config.bst
- freedesktop-sdk.bst:components/gettext.bst
- freedesktop-sdk.bst:components/vala.bst

depends:
- freedesktop-sdk.bst:public-stacks/runtime-minimal.bst
- deps/packagekit-glib2.bst
- gnome-build-meta.bst:core-deps/libportal.bst
- freedesktop-sdk.bst:components/gsettings-desktop-schemas.bst
- gnome-build-meta.bst:sdk/gtk.bst
- gnome-build-meta.bst:sdk/libadwaita.bst
- deps/granite-7.bst
- desktop/panel/wingpanel.bst
